<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bakos" failures="0" tests="2" name="Test" time="0.155" errors="0" timestamp="2024-03-10T11:30:33 CDT">
  <testcase classname="testCases.BaseClass" name="@BeforeMethod SetUp" time="0.018">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testCases.BaseClass.SetUp(BaseClass.java:22)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod SetUp -->
  <testcase classname="testCases.BaseClass" name="@AfterMethod TearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase classname="testCases.BaseClass" name="@BeforeMethod SetUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod SetUp -->
  <testcase classname="testCases.BaseClass" name="@AfterMethod TearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase classname="testCases.LoginTest" name="LoginFailureTest" time="0.0">
    <skipped/>
  </testcase> <!-- LoginFailureTest -->
  <testcase classname="testCases.LoginTest" name="LoginSuccessTest" time="0.001">
    <skipped/>
  </testcase> <!-- LoginSuccessTest -->
</testsuite> <!-- Test -->
